### PR TITLE
Run build on `prepublishOnly`

### PR DESCRIPTION
**Pull request by styfle**
The current `postinstall` script will run for anyone attempting to `npm install ronin` and will fail if they are missing `bun` in their PATH.

I think the intention here is to run a build before publishing to the registry so you can use `prepublishOnly` instead.

See https://docs.npmjs.com/cli/v10/using-npm/scripts

### CODE REVIEW

**Review by leo — APPROVED** [review]

**Comment by styfle** [comment]
Perhaps. Package Phobia runs arbitrary code (afterall, thats what npm is) so I dont really want to expose the error message for security reasons.

**Comment by styfle** [comment]
Looks like CI is failing on main because of the the `bun.lockb` file is outdated

**Comment by leo** [comment]
It's unclear to me why the CI of the current PR says that the Bun lockfile is outdated while all previous PRs don't, but perhaps it is related to the fact that the cache of those PRs is not shared with external (contributor) PRs.

CleanShot 2024-06-12 at 19 59 09@2x

**Comment by leo** [comment]
Thank you so much for your change! I landed it in https://github.com/ronin-co/client/pull/65 due to the aforementioned issue.

The badge seems to be working again! 🎉

**Pull request closed without merging**
